# Site settings
title: Events - Open Source Design
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more open design processes and improve the design of open source apps
baseurl: "/events/"
url: "http://opensourcedesign.net"

twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
permalink: /:year-:month-:day/:title

# Show future events
future: True

# Enable the redirect_from plugin
gems:
  - jekyll-redirect-from

status: &status
  - name: "Upcoming"
    value: "upcoming"
  - name: "Started"
    value: "started"
  - name: "Past"
    value: "Past"
  - name: "Cancelled"
    value: "cancelled"

# Prose Config - what is seen at https://edit.opensourcedesign.net
# Docs: https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 'events'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "event"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "status"
        field:
          element: "select"
          label: "Event Status"
          placeholder: "Event Status"
          options: *status
          selected: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Tags"
          value: ""
